### ISSUE TITLE
Newton Method

### ISSUE THREAD

**Issue by Memphis99** [CMM-22/a6#1]
Hello, for point 4 I implemented the objective function with the regularizer on |u|^2. When I start the simulation with GD, all goes smoothly, but when I simulate with Newton Method, it does optimize the trajectory, but all the app and the simulation gets laggy and really slow. I tried using different log_c_reg but it lags everytime.
Am I making some errors? Could be the app's problem?

**Comment by joshuaoreilly** [comment]
I also have a lot of lag, even in release mode. Not sure if it's normal.

**Comment by MiguelZamoraM** [comment]
This Is normal. The point is that we are computing both the gradient and  the Hessian using finite differences, and that requires a lot of compute. 
Recall that if it gets laggy and you want to stop the optimization you can press the letter "o" in your keyboard.

**Comment by Memphis99** [comment]
Ok thank you!
