### ISSUE TITLE
Ex. 8 Why will sim shadow and transcription trajectory not match?

### ISSUE THREAD

**Issue by owlxof** [CMM-22/a6#12]
After copying the stepExplixitEuler to the transcription app and implementing the objective function there, both the transcription and the simulated trajectory behave completely unexpected. Is this due to bugs in my objective function or am I missing a different part in how this all should be pieced together?

The first screenshot shows the trajectories at startup and the second one shows them after optimization.
![screenshot_20220526_191837](https://user-images.githubusercontent.com/16327166/170542245-b10a8c62-8605-470e-b975-20677aa7bb88.png)
![screenshot_20220526_191542](https://user-images.githubusercontent.com/16327166/170542264-d9d48362-7cec-4511-808c-b6fb78e22ead.png)

**Comment by owlxof** [comment]
Solved: The physics constraints were off because in the precomputation of 1/h, I had `.1/h` instead of `1./h `.

**Comment by MiguelZamoraM** [comment]
Did you add an objective to enforce the state trajectory to be physically valid? If you implemented such an objective correctly then it should be a matter of increasing the weight/coefficient of that objective.
