### ISSUE TITLE
How to see number of optimization steps?

### ISSUE THREAD

**Issue by joshuaoreilly** [CMM-22/a6#2]
For question 5:

> Try optimizing for a few different targets with Newton’s method. **How many
steps** does Newton’s method usually take to converge for this problem? Why?

Is there some UI element that tells us how many iterations the solvers take to converge, or do we have to program that ourselves?

Thanks!

**Comment by MiguelZamoraM** [comment]
You can always add stuff to the UI or print stuff to the console. Moreover,  I encourage you to think about it from a theoretical point of view and then see if the experiment matches your reasoning.
